// <auto-generated />
using BlogsApp.Infrastracture;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastracture.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20200601093752_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogsApp.Infrastracture.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("BlogsApp.Infrastracture.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            Title = "Some scientific title 1"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 1,
                            Content = "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).",
                            Title = "Some scientific title 2"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 1,
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eu turpis vitae felis mattis finibus. Duis a erat ac elit iaculis pellentesque quis congue justo. Nam ut velit vitae orci ullamcorper consequat. Pellentesque eget velit non tellus lobortis tempus. Curabitur egestas libero vitae lacus ullamcorper maximus. Suspendisse nisl justo, sollicitudin sit amet quam id, rhoncus pellentesque arcu. Pellentesque at magna mi. Maecenas a maximus orci. Proin a ipsum eu ante accumsan interdum ut at lacus. Nam nibh tellus, tincidunt imperdiet arcu sed, venenatis sollicitudin sem. Curabitur quis facilisis velit. Curabitur ornare ultricies mauris, a blandit quam ultricies quis. Donec lobortis, diam ac pulvinar facilisis, ipsum velit interdum nisi, sit amet laoreet est eros elementum justo. In hac habitasse platea dictumst.",
                            Title = "Some scientific title 3"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 1,
                            Content = "Vestibulum ut tellus vulputate, pretium nunc ac, ultrices diam. Vivamus non egestas lectus, ac ultricies quam. Pellentesque ac ex in magna pellentesque volutpat quis scelerisque elit. Aliquam erat volutpat. Aliquam ac consequat neque. Nulla eros urna, egestas nec metus id, aliquet consectetur urna. Maecenas tempor nibh et convallis congue. Donec eu mi fermentum, congue sapien nec, malesuada leo. Praesent nec nunc hendrerit quam malesuada semper sit amet eget augue. Ut laoreet rutrum nunc, quis lacinia lacus pellentesque gravida. Vivamus luctus magna in mauris interdum, vitae rhoncus lacus ornare. Cras sagittis cursus magna, quis mattis orci lacinia a.",
                            Title = "Some scientific title 4"
                        },
                        new
                        {
                            PostId = 5,
                            BlogId = 1,
                            Content = "Maecenas dapibus turpis ut risus tincidunt placerat ut sit amet dui. Vivamus eget elit non quam efficitur tristique nec id velit. Nunc in rhoncus libero. Proin nec ante nunc. Donec ac erat elit. Nunc blandit diam tortor, accumsan elementum sem facilisis vel. Donec nec consequat neque. Integer ultrices pulvinar lacus. Nam id dignissim turpis, ac iaculis ex. Donec sit amet pulvinar nunc. Vivamus hendrerit, ligula a pharetra dapibus, mauris tortor condimentum eros, nec lacinia odio ante malesuada elit. Nunc eleifend fringilla odio, sit amet posuere urna aliquet vel. Quisque in eros in mauris suscipit cursus. Proin ligula erat, luctus a viverra sit amet, finibus vel quam. Fusce egestas luctus leo, ut dictum sapien.",
                            Title = "Some scientific title 5"
                        });
                });

            modelBuilder.Entity("BlogsApp.Infrastracture.Post", b =>
                {
                    b.HasOne("BlogsApp.Infrastracture.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
